version: "3.7"

networks:
  decert-app:
    driver: bridge

services:
  mysql:
    container_name: decert-mysql
    image: 'bitnami/mysql:latest'
    volumes:
      - ./volumes/mysql/data:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=decert
    networks:
      - decert-app
    ports:
      - "3406:3306"